import { useState } from 'react'
import type { Channel } from '../types'
import { generateFallbackThumbnail } from '../utils/thumbnailFallback'

interface ChannelCardProps {
  channel: Channel
  index: number
  isSelected: boolean
  onSelect: (index: number) => void
  overrideImage?: string | null
  isFavorite?: boolean
  onToggleFavorite?: (channelId: string) => void
}

function getSourceFromId(id: string): 'kexp' | 'somafm' | 'rp' | 'nts' | null {
  if (id.startsWith('kexp:')) return 'kexp'
  if (id.startsWith('somafm:')) return 'somafm'
  if (id.startsWith('rp:')) return 'rp'
  if (id.startsWith('nts:')) return 'nts'
  return null
}

function getSourceBadgeLabel(source: 'kexp' | 'somafm' | 'rp' | 'nts'): string {
  switch (source) {
    case 'kexp': return 'KEXP'
    case 'rp': return 'RP'
    case 'nts': return 'NTS'
    default: return 'SF'
  }
}

// Radio Paradise logo as fallback when no album art available
const RP_FALLBACK_IMAGE = 'https://img.radioparadise.com/logos/rp_logo_128.png'

// Generate seeded random number from string - using mulberry32 algorithm
function seededRandom(seed: string, index: number): number {
  let h = 0
  const str = seed + '_' + index
  for (let i = 0; i < str.length; i++) {
    h = Math.imul(h ^ str.charCodeAt(i), 2654435761)
  }
  h = Math.imul(h ^ (h >>> 16), 2654435761)
  h = Math.imul(h ^ (h >>> 16), 2654435761)
  return (h >>> 0) / 4294967296
}

// Generate random circles for NTS thumbnails
function generateCircles(channelId: string): React.CSSProperties[] {
  const circles: React.CSSProperties[] = []
  const numCircles = 3 + Math.floor(seededRandom(channelId, 0) * 4) // 3-6 circles

  for (let i = 0; i < numCircles; i++) {
    const size = 25 + seededRandom(channelId, i + 100) * 50 // 25-75%
    const left = 10 + seededRandom(channelId, i + 200) * 80 // 10-90%
    const top = 10 + seededRandom(channelId, i + 300) * 80 // 10-90%
    const opacity = 0.1 + seededRandom(channelId, i + 400) * 0.2 // 0.1-0.3

    circles.push({
      position: 'absolute',
      width: `${size}%`,
      height: `${size}%`,
      left: `${left}%`,
      top: `${top}%`,
      borderRadius: '50%',
      background: `rgba(255, 255, 255, ${opacity})`,
      transform: 'translate(-50%, -50%)',
      pointerEvents: 'none',
    })
  }
  return circles
}

function ChannelCard({ channel, index, isSelected, onSelect, overrideImage, isFavorite = false, onToggleFavorite }: ChannelCardProps) {
  const source = getSourceFromId(channel.id)
  const isKexp = source === 'kexp'
  const isNts = source === 'nts'
  const [imageError, setImageError] = useState(false)
  const [failedImage, setFailedImage] = useState<string>('')
  const [isSmallImage, setIsSmallImage] = useState(false)

  // Check if channel has artworkConfig specifying auto-generated thumbnail
  const useAutoGenerated = channel.artworkConfig?.thumbnail === 'auto-generated'

  // Use override image if provided, otherwise channel default, with RP fallback
  const imageUrl = overrideImage
    ?? channel.image.medium
    ?? (source === 'rp' ? RP_FALLBACK_IMAGE : '')

  // Reset error state when image changes
  if (imageUrl !== failedImage && imageError) {
    setImageError(false)
    setFailedImage('')
  }

  // Generate fallback thumbnail data
  // Use fallback if: 1) artworkConfig says auto-generated, OR 2) image failed to load
  // Pass false for isHeroView since this is the carousel thumbnail
  const fallback = generateFallbackThumbnail(
    channel.id,
    channel.title,
    (useAutoGenerated || imageError) ? '' : imageUrl,
    false
  )
  
  // Override fallback properties if artworkConfig is present
  if (useAutoGenerated && channel.artworkConfig) {
    fallback.backgroundColor = channel.artworkConfig.backgroundColor || fallback.backgroundColor
    fallback.initials = channel.artworkConfig.displayText || fallback.initials
    fallback.needsFallback = true
  }

  const handleFavoriteClick = (e: React.MouseEvent) => {
    e.stopPropagation()
    onToggleFavorite?.(channel.id)
  }

  const handleImageError = () => {
    setImageError(true)
    setFailedImage(imageUrl)
  }

  const handleImageLoad = (e: React.SyntheticEvent<HTMLImageElement>) => {
    const img = e.currentTarget
    // Check if image is smaller than 50px in either dimension
    if (img.naturalWidth < 50 || img.naturalHeight < 50) {
      setIsSmallImage(true)
    } else {
      setIsSmallImage(false)
    }
  }

  return (
    <div
      className={`carousel-item ${isSelected ? 'selected' : ''}`}
      onClick={() => onSelect(index)}
    >
      <div className="carousel-item-image-wrapper">
        {isKexp ? (
          <div className="kexp-logo-container">
            <img src="https://www.kexp.org/static/assets/img/logo-header.svg" alt="KEXP" />
          </div>
        ) : isNts ? (
          <div className="nts-logo-container" style={{ backgroundColor: channel.bgColor || '#1a1a1a' }}>
            {generateCircles(channel.id).map((style, i) => (
              <div key={i} style={style} />
            ))}
            <img src={channel.image.medium} alt="" className="nts-logo-blur" />
            <img src={channel.image.medium} alt="NTS" className="nts-logo-img" />
          </div>
        ) : fallback.needsFallback ? (
          <div
            className={`fallback-thumbnail ${fallback.displayMode === 'full-name' ? 'fallback-full-name' : ''} ${fallback.style ? `fallback-${fallback.style}` : ''}`}
            style={{
              backgroundColor: fallback.backgroundColor,
              '--fallback-color-1': fallback.backgroundColor,
              '--fallback-color-2': fallback.backgroundColor + 'dd',
            } as React.CSSProperties}
          >
            {fallback.displayMode === 'full-name' ? (
              <span className="fallback-name-text">{fallback.fullName}</span>
            ) : (
              <span className="fallback-initials">{fallback.initials}</span>
            )}
          </div>
        ) : isSmallImage ? (
          <div className="small-logo-container">
            <img
              src={imageUrl}
              alt={channel.title}
              onError={handleImageError}
              onLoad={handleImageLoad}
            />
          </div>
        ) : (
          <img
            src={imageUrl}
            alt={channel.title}
            onError={handleImageError}
            onLoad={handleImageLoad}
          />
        )}
        {source && !isKexp && !isNts && <span className={`source-badge source-${source}`}>{getSourceBadgeLabel(source)}</span>}
        <button
          className={`favorite-btn ${isFavorite ? 'is-favorite' : ''}`}
          onClick={handleFavoriteClick}
          aria-label={isFavorite ? 'Remove from favorites' : 'Add to favorites'}
        >
          <span className="material-symbols-outlined">favorite</span>
        </button>
      </div>
      <span className="carousel-item-title">{channel.title}</span>
    </div>
  )
}

export default ChannelCard
